//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theforum.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("theforum.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChangePasswordNewPasswordMustNotMatchOld {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordMustNotMatchOld", resourceCulture);
            }
        }
        
        internal static string ChangePasswordOldPasswordNotCorrect {
            get {
                return ResourceManager.GetString("ChangePasswordOldPasswordNotCorrect", resourceCulture);
            }
        }
        
        internal static string ChangePasswordUserAccountEmailAddressNotFound {
            get {
                return ResourceManager.GetString("ChangePasswordUserAccountEmailAddressNotFound", resourceCulture);
            }
        }
        
        internal static string CreatePostMessageError {
            get {
                return ResourceManager.GetString("CreatePostMessageError", resourceCulture);
            }
        }
        
        internal static string CreatePostMustBeLoggedIn {
            get {
                return ResourceManager.GetString("CreatePostMustBeLoggedIn", resourceCulture);
            }
        }
        
        internal static string CreatePostParentPostNotFound {
            get {
                return ResourceManager.GetString("CreatePostParentPostNotFound", resourceCulture);
            }
        }
        
        internal static string CreatePostThreadNotFound {
            get {
                return ResourceManager.GetString("CreatePostThreadNotFound", resourceCulture);
            }
        }
        
        internal static string CreatePostTitleError {
            get {
                return ResourceManager.GetString("CreatePostTitleError", resourceCulture);
            }
        }
        
        internal static string CreatePostUserAccountNotFound {
            get {
                return ResourceManager.GetString("CreatePostUserAccountNotFound", resourceCulture);
            }
        }
        
        internal static string CreateThreadMessageError {
            get {
                return ResourceManager.GetString("CreateThreadMessageError", resourceCulture);
            }
        }
        
        internal static string CreateThreadMustBeLoggedIn {
            get {
                return ResourceManager.GetString("CreateThreadMustBeLoggedIn", resourceCulture);
            }
        }
        
        internal static string CreateThreadTitleError {
            get {
                return ResourceManager.GetString("CreateThreadTitleError", resourceCulture);
            }
        }
        
        internal static string CreateThreadUserAccountNotFound {
            get {
                return ResourceManager.GetString("CreateThreadUserAccountNotFound", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmailAddressDuplicate {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressDuplicate", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmailAddressNoAtSymbol {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressNoAtSymbol", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmailAddressNoDotSymbol {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressNoDotSymbol", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmailAddressTooLong {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressTooLong", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmptyEmailAddress {
            get {
                return ResourceManager.GetString("CreateUserAccountEmptyEmailAddress", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountEmptyUsername {
            get {
                return ResourceManager.GetString("CreateUserAccountEmptyUsername", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountPasswordMustBeSupplied {
            get {
                return ResourceManager.GetString("CreateUserAccountPasswordMustBeSupplied", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountPasswordsMustMatch {
            get {
                return ResourceManager.GetString("CreateUserAccountPasswordsMustMatch", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountUsernameDuplicate {
            get {
                return ResourceManager.GetString("CreateUserAccountUsernameDuplicate", resourceCulture);
            }
        }
        
        internal static string CreateUserAccountUsernameTooLong {
            get {
                return ResourceManager.GetString("CreateUserAccountUsernameTooLong", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordPasswordMustBeSupplied {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordMustBeSupplied", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordPasswordsMustMatch {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordsMustMatch", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordPasswordTooShort {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordTooShort", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordTokenExpired {
            get {
                return ResourceManager.GetString("UpdatePasswordTokenExpired", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordTokenIncorrect {
            get {
                return ResourceManager.GetString("UpdatePasswordTokenIncorrect", resourceCulture);
            }
        }
        
        internal static string UpdatePasswordUserAccountNotFound {
            get {
                return ResourceManager.GetString("UpdatePasswordUserAccountNotFound", resourceCulture);
            }
        }
        
        internal static string UserAccountNotActivated {
            get {
                return ResourceManager.GetString("UserAccountNotActivated", resourceCulture);
            }
        }
        
        internal static string UserAccountPasswordNoAlphabetCharacters {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoAlphabetCharacters", resourceCulture);
            }
        }
        
        internal static string UserAccountPasswordNoNonAlphanumericCharacter {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoNonAlphanumericCharacter", resourceCulture);
            }
        }
        
        internal static string UserAccountPasswordNoNumericCharacter {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoNumericCharacter", resourceCulture);
            }
        }
        
        internal static string UserAccountPasswordTooLong {
            get {
                return ResourceManager.GetString("UserAccountPasswordTooLong", resourceCulture);
            }
        }
        
        internal static string UserAccountPasswordTooShort {
            get {
                return ResourceManager.GetString("UserAccountPasswordTooShort", resourceCulture);
            }
        }
        
        internal static string UserAccountUserIdNotFound {
            get {
                return ResourceManager.GetString("UserAccountUserIdNotFound", resourceCulture);
            }
        }
        
        internal static string ValidateUserAccountEmailNotFound {
            get {
                return ResourceManager.GetString("ValidateUserAccountEmailNotFound", resourceCulture);
            }
        }
        
        internal static string ValidateUsernameNotFound {
            get {
                return ResourceManager.GetString("ValidateUsernameNotFound", resourceCulture);
            }
        }
    }
}
