version: '3.8'
services:
  theforum_app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env
    depends_on:
      theforum_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://localhost:443/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/Debug/net7.0:/app
  theforum_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: .env.db
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", 
              "-U", "sa", "-P", "abc@12345", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

